arm:
  type: ur10
  initial_joint_states:
    linear_arm_actuator_joint: 0
# sensors:
#   logical_camera_1:
#     type: logical_camera
#     pose:
#       xyz: [-0.7, -0.15, 3.5]
#       rpy: [0, 'pi/2', 0]
sensors:
  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [0, 0.5, 5]
      rpy: [0, 'pi/2', 0]
  laser_profiler_1:
    type: laser_profiler
    pose:
      xyz: [1.21816, 4, 1.24]
      rpy: ['-pi', 'pi/2', 'pi/2']
